// <auto-generated />
using Biblioteca.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Biblioteca.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20250425194110_Criacao-Sinopse")]
    partial class CriacaoSinopse
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("Biblioteca.Models.Livro", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("Id");

                    b.Property<string>("AnoPublicacao")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Data de Publicação");

                    b.Property<string>("Autor")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Autor");

                    b.Property<string>("Sinopse")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Sinopse");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("Titulo");

                    b.HasKey("Id");

                    b.ToTable("Livros");
                });
#pragma warning restore 612, 618
        }
    }
}
